### ISSUE TITLE
How about preview?

### ISSUE THREAD

**Issue by denysdovhan** [chriskempson/base16-gnome-terminal#10]
I just want to propose you add some screenshots with preview. I think, with screenshots it will be easier to chose theme, that user would like. How about this idea?

**Comment by kusold** [comment]
@denysdovhan You can preview the colors here: https://chriskempson.github.io/base16/

That site is more geared towards text editors, but it lets you see how all the colors look together.

Here is my screenshot using eighties:
![image](https://cloud.githubusercontent.com/assets/509966/13657416/625a3e60-e62c-11e5-9c7e-6e8236d0dc09.png)
