### ISSUE TITLE
Sourcing Each Script via For loop Crashes Gnome Terminal

### ISSUE THREAD

**Issue by barberousse** [chriskempson/base16-gnome-terminal#24]
`#! /usr/bin/env bash
for FILE in ./*sh; do
    source $FILE
done
`
Crashes Gnome Terminal immediately with the side effect that only the first base16 profile is installed.

EDIT: Running Gnome 3.18 on Xenial with uuidgen and dconf installed

**Comment by lukaszkarbownik** [comment]
Hey,
I'm not sure what's causing this, but you can do `/usr/bin/env bash for FILE in ./*sh; do bash $FILE done` as a quick solution to import all themes at once.
