### ISSUE TITLE
I need to uninstall

### ISSUE THREAD

**Issue by Asumerodi** [chriskempson/base16-gnome-terminal#26]
trying to revert back to solarized but this script seems to have done something to mess up how the terminal handles profiles what the heck do I need to do to undo what it did.

**Comment by ondrejtichacek** [comment]
I ran into the same problem, managed to solve it by executing

    dconf reset -f /org/gnome/terminal/

You need to have `dconf-tools` installed.

This was in Ubuntu 16.04
