### ISSUE TITLE
Gnome terminal and vim issues

### ISSUE THREAD

**Issue by gns-ank** [chriskempson/base16-gnome-terminal#5]
I observe a very similar issue to the one described bellow:
<https://github.com/chriskempson/base16-vim/issues/44>

Has there been any work done towards fixing it? Thanks.

I have run the base16-gnome-terminal to get the colorscheme and have a base16-shell script in my `.zshrc`. The $TERM is set to "xterm-256color" and I run Ubuntu 12.04.

vim in gnome-terminal:
![screenshot from 2014-08-28 09 51 46](https://cloud.githubusercontent.com/assets/240938/4073135/e277e098-2e90-11e4-9802-374234ab2109.png)

gvim:
![screenshot from 2014-08-28 09 54 54](https://cloud.githubusercontent.com/assets/240938/4073157/261d1b92-2e91-11e4-9d66-637f7c1c67a3.png)

**Comment by xHN35RQ** [comment]
Upgrade to latest Gnome Terminal, I'm on 3.14.2 and get full colors using only the base16-shell scripts.

**Comment by gns-ank** [comment]
I can confirm that with the latest Gnome Terminal I can reproduce the issue anymore.
