### ISSUE TITLE
How is this installed? Please add installation/setup notes to blank README

### ISSUE THREAD

**Issue by jnachtigall** [chriskempson/base16-gnome-terminal#6]
How is this installed? I executed `source .config/base16-gnome-terminal/base16-default.dark.sh` in gnome-terminal, but no changes at all (Ubuntu 14.04).

I searched the web for 1h about how to get base16-default-dark colors in gnome-terminal and no-gui vim, but no success.

Please add some installation and setup notes to the README

**Comment by shime** [comment]
It adds new profile to your gnome terminal. right click on terminal -> profiles and you should see `base16 default` there.

**Comment by jnachtigall** [comment]
ok, thanks! maybe such minimal information should be added to the Readme

**Comment by shime** [comment]
Yup, that would be great!

**Comment by chriskempson** [comment]
Don't have a Linux box handy to test with at the moment but I'll try and add this info to the install. Just to be clear, do you have to source one of the files and after this the file will appear as a selectable theme in Gnome Terminal?

**Comment by shime** [comment]
@chriskempson yup, that's how it works.

**Comment by chriskempson** [comment]
Added some instructions. Hope they are okay.
